### PR TITLE
Add the "create /ipfs and /ipns" step

### PR DESCRIPTION
**Pull request by daviddias**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
:+1:

**Comment by whyrusleeping** [comment]
might also refer people to our fuse guide: https://github.com/ipfs/go-ipfs/blob/master/docs/fuse.md

**Comment by jbenet** [comment]
+1 to refer people to fuse guide. @diasdavid mind throwing that in and then will merge?
- [ ] add reference to fuse guide.

**Comment by daviddias** [comment]
Certainly, just added a reference.

**Comment by jbenet** [comment]
LGTM

**Pull request merged**
