### PR TITLE
Fix compilation of api/service/{client,host}.go examples

### PR DESCRIPTION
**Pull request by inetic**

### CODE REVIEW

**Comment by hsanjuan** [comment]
@inetic problem is, this will break again as soon as libp2p-peer is updated in go-ipfs. I'm not sure what the best way to proceed here would be.

@Kubuxu ideas?

**Comment by inetic** [comment]
@hsanjuan I see what you mean, I'll just point out that if this is a problem then it's a problem in https://github.com/ipfs/go-ipfs as well. That is how I found the solution actually, by doing

```
$ cd <go-ipfs-src-dir> && grep '\<peer\>\s\+\"' * -rI
cmd/seccat/seccat.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/bootstrap.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/mock/mock.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/builder.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/corenet/net.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/commands/publish.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/commands/bitswap.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/commands/keystore.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/commands/dht.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/commands/ping.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/commands/stat.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
core/core.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
diagnostics/vis.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
diagnostics/diag.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/testnet/interface.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/testnet/network_test.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/testnet/peernet.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/testnet/virtual.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/bitswap.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/wantmanager.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/testutils.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/decision/ledger.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/decision/engine_test.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/decision/engine.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/decision/peer_request_queue.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/workers.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/network/interface.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
exchange/bitswap/network/ipfs_impl.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
fuse/ipns/ipns_unix.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
namesys/republisher/repub.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
namesys/resolve_test.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
namesys/namesys.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
namesys/publisher.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
repo/config/init.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
routing/supernode/client.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
routing/supernode/proxy/loopback.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
routing/supernode/proxy/standard.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
routing/supernode/server.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
routing/none/none_client.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
routing/mock/interface.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
routing/mock/centralized_server.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
routing/mock/centralized_client.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
thirdparty/testutil/identity.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
thirdparty/testutil/gen.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
thirdparty/ipfsaddr/ipfsaddr.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
thirdparty/ipfsaddr/ipfsaddr_test.go:	peer "gx/ipfs/QmWUswjn261LSyVxWAEpMVtPdy8zmKBJJfBpG3Qdpa8ZsE/go-libp2p-peer"
```

**Comment by whyrusleeping** [comment]
Hrm... This issue should get a lot better if we can extract more packages here out from the main go-ipfs codebase.

I think we can merge this, but lets first add a comment explaining how to fix it easily if its broken again

**Comment by hsanjuan** [comment]
@inetic also you can also make subfolders for each of the commands, as they cannot be built in the same folder anyway.

**Comment by inetic** [comment]
@hsanjuan, sorry for the delay. I added a comment about how to fix the 'peer' import if it breaks in the future. Also, me being new to go (I have literally only worked with these two files so far), I'm not sure I understand the request for subfolders. Do you mean to create this file structure?

```
api/service/host/host.go
api/service/client/client.go
api/service/readme.md
```
I also don't understand the "they cannot be built in the same folder" comment. I could easily do

```
$ go build client.go # builds `client` executable
$ go build host.go # builds `host` executable
```
Would you please care to explain?

**Comment by hsanjuan** [comment]
@inetic you're right, nevermind.

**Comment by Kubuxu** [comment]
Let's merge it, it is better than what exists currently and we can always improve upon.

**Pull request merged**
