### PR TITLE
Fixing `Be the Swarm` example up a bit

### PR DESCRIPTION
**Pull request by RichardLitt**
See https://github.com/ipfs/website/issues/134

### CODE REVIEW

**Comment by whyrusleeping** [comment]
LGTM

**Comment by RichardLitt** [comment]
@lgierth Adjust the website?

**Comment by ghost** [comment]
I've never updated the examples on the website, not sure if there's a tool or you simple change the hashes in the examples page

**Comment by RichardLitt** [comment]
Looks like we need to update the entire examples page hash. https://ipfs.io/ipfs/QmQwAP9vFjbCtKvD8RkJdCvPHqLQjZfW7Mqbbqx18zd8j7 is no longer correct. I updated it in the two linked PRs.

**Pull request merged**
